appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: WDSbpqT2XRuAyAEM8A5mTo0OHGff8CL9bmQ0N64tMRBlM7pVVZprGRlaIhgLQCl1VH3FPXdy2mYBsYzMkJ1j7tNrlS3Ch7xxa4bD7WK6h8q1EimGaTqQ8nhc10WjktznIYBqQpOnpHnQNhX/3gqdj1Sk5YPG6H3JxdYIicFXMTlxeaIPj9LmIEFL/qx0Y6tSDApLBaJWt5cS0CQeo+YNrUUx14WiOnMzeKIjGCHkGzoWAVmqprPJjknebVpofxPlZQeWDG8UkIXXIRWnPgaO5q4vpaAfpixFjqXZozh4/KRvBbXc2FTap4K3IMH2qIObX/m5HKMpBGuvAv8Etp/XnsrB4aLs3a2UcZlKC8WMN+idr0znTjpyWJv951dxJYHDMFWbeG0eDCXxYgeTPFF+Ymm226AQgBTmWBlStw/mvOAQ7zPdMTDkYacumVYT9FXlljCoe/spOFYiiAdZKPN8YZXxr2FLnaAXWWuoA0PMoU+6MdGh4k6P4Ocfscz1zU6X3jdBMACAFJJIrQcTQEC8KM9AkewUlfsebqPu8lpzsn79eHCaNljIlN4dpqZ/IlG4+9wUNckX1HbIVrIDI26HJZIN1cs3QL9mhBLQ9b1ziVPn93zFEFNjmMuI55af/wvXWl3ioZBSu6QZQui5QA+ezj/B0PkikVGKTPFl50nPHTQ=
conda_forge_output_validation: true
